// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PATH/main/proto/OauthService.proto

package com.example.DemoGraphQL.grpc;

public final class OauthServiceOuterClass {
  private OauthServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_DemoGraphQL_grpc_OauthRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_DemoGraphQL_grpc_OauthRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_DemoGraphQL_grpc_OauthResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_DemoGraphQL_grpc_OauthResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"PATH/main/proto/OauthService.proto\022\034co" +
      "m.example.DemoGraphQL.grpc\"]\n\014OauthReque" +
      "st\022\025\n\rAuthorization\030\001 \001(\t\022\022\n\ngrant_type\030" +
      "\002 \001(\t\022\020\n\010username\030\003 \001(\t\022\020\n\010password\030\004 \001(" +
      "\t\"s\n\rOauthResponse\022\024\n\014access_token\030\001 \001(\t" +
      "\022\022\n\ntoken_type\030\002 \001(\t\022\025\n\rrefresh_token\030\003 " +
      "\001(\t\022\022\n\nexpires_in\030\004 \001(\005\022\r\n\005scope\030\005 \001(\t2t" +
      "\n\014OauthService\022d\n\tloginUser\022*.com.exampl" +
      "e.DemoGraphQL.grpc.OauthRequest\032+.com.ex" +
      "ample.DemoGraphQL.grpc.OauthResponseB\002P\001" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_example_DemoGraphQL_grpc_OauthRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_DemoGraphQL_grpc_OauthRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_DemoGraphQL_grpc_OauthRequest_descriptor,
        new java.lang.String[] { "Authorization", "GrantType", "Username", "Password", });
    internal_static_com_example_DemoGraphQL_grpc_OauthResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_example_DemoGraphQL_grpc_OauthResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_DemoGraphQL_grpc_OauthResponse_descriptor,
        new java.lang.String[] { "AccessToken", "TokenType", "RefreshToken", "ExpiresIn", "Scope", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
