// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PATH/main/proto/OauthService.proto

package com.example.DemoGraphQL.grpc;

public interface OauthResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.DemoGraphQL.grpc.OauthResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string access_token = 1;</code>
   */
  java.lang.String getAccessToken();
  /**
   * <code>string access_token = 1;</code>
   */
  com.google.protobuf.ByteString
      getAccessTokenBytes();

  /**
   * <code>string token_type = 2;</code>
   */
  java.lang.String getTokenType();
  /**
   * <code>string token_type = 2;</code>
   */
  com.google.protobuf.ByteString
      getTokenTypeBytes();

  /**
   * <code>string refresh_token = 3;</code>
   */
  java.lang.String getRefreshToken();
  /**
   * <code>string refresh_token = 3;</code>
   */
  com.google.protobuf.ByteString
      getRefreshTokenBytes();

  /**
   * <code>int32 expires_in = 4;</code>
   */
  int getExpiresIn();

  /**
   * <code>string scope = 5;</code>
   */
  java.lang.String getScope();
  /**
   * <code>string scope = 5;</code>
   */
  com.google.protobuf.ByteString
      getScopeBytes();
}
