// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PATH/main/proto/OauthService.proto

package com.example.DemoGraphQL.grpc;

public interface OauthRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.DemoGraphQL.grpc.OauthRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Authorization = 1;</code>
   */
  java.lang.String getAuthorization();
  /**
   * <code>string Authorization = 1;</code>
   */
  com.google.protobuf.ByteString
      getAuthorizationBytes();

  /**
   * <code>string grant_type = 2;</code>
   */
  java.lang.String getGrantType();
  /**
   * <code>string grant_type = 2;</code>
   */
  com.google.protobuf.ByteString
      getGrantTypeBytes();

  /**
   * <code>string username = 3;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 3;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string password = 4;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 4;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
